version: "3"

services:
    django:
        build: .
        ports:
            - ${DJANGO_PORT}:8000
        # command: bash -c "while true; do echo 'I am alive!'; sleep 3600; done"
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - C_FORCE_ROOT=true
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - .:/webapp
        links:
            - postgres
            - redis

    celeryw:
        build: .
        command: celery -A comments worker -l info
        environment:
            - C_FORCE_ROOT=true
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - .:/webapp
        links:
            - postgres
            - redis

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - postgres-volume:/var/lib/postgresql/data
            - ./etc/postgres-entrypoint:/docker-entrypoint-initdb.d

    redis:
        image: redis:3.2
        volumes:
            - redis-volume:/data

volumes:
    postgres-volume:
    redis-volume:
